### ISSUE TITLE
Problem: toc styling is wrong

### ISSUE THREAD

**Issue by sappo** [zeromq/gitdown#12]
There is a problem with the construction of the toc. Somehow the first second level header after the toc declaration has wrong styling. This issue can be seen in the zyre README: https://github.com/zeromq/zyre/blob/master/README.md .

**Comment by hintjens** [comment]
I can't reproduce this with gitdown; it generates the correct TOC for me (I
pushed a correct README.md...) Does this happen on the latest version of
gitdown?

**Comment by sappo** [comment]
Yes, this happens with the latest version. Just cloned a fresh copy from github to double check. Also the version you pushed to zyre is missing the hint on how this document has been created: https://github.com/zeromq/gitdown/blob/315392d01ece5867e7a11fafdda74372a8cb4228/bin/gitdown#L199. Thus it seems to me you're using an older version where the toc is generated correct.

**Comment by hintjens** [comment]
Huh, I suspect 2cc2145 might have something to do with it.
