### ISSUE TITLE
Markdown syntax highlighting

### ISSUE THREAD

**Issue by papr** [zeromq/gitdown#18]
The `gitdown` [Markdown Syntax Summary](https://github.com/zeromq/gitdown#toc2-226) mentions that it produces code blocks by indenting them. I suggest a transition to [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) since they allow syntax highlighting.

Since `gitdown` is used in many projects to generate documentation from source code, I suggest one could use the source files' file endings to enable syntax highlighting automatically for all projects using `gitdown`. This would improve the readability of the documentation of projects like `czmq` by a wide margin.

**Comment by hintjens** [comment]
yes, we can support both. send a pulk request?

**Comment by papr** [comment]
I am sorry but I do not have any experience with `Perl`. :-/

**Comment by papr** [comment]
After doing some reading, I think this is not the right place to implement this feature. Fenced code blocks are actually supported by `gitdown` already.

The right place to implement this feature would be the software which generates the `*.doc` files from the source files. Which software is this?

**Comment by sappo** [comment]
`doc/mkman` generates the `*.doc` files which is in turn generated by zproject. The correspoding function that pulls content from sources and headers is: https://github.com/zeromq/zproject/blob/master/zproject_autotools.gsl#L980.

**Comment by papr** [comment]
So what is the correct behaviour now? Should we close this issue and reopen it at `zproject`?

**Comment by sappo** [comment]
Nope, we can add it to both!

**Comment by sappo** [comment]
@papr czmq's code blocks are now colorful ;) check it out!

**Comment by papr** [comment]
It is so pretty! Now the documentation for all zmq projects has to be updated and then we are good to go. :)

Thank you very much for solving the issue so fast!
